services:
  database:
    image: postgres:alpine
    container_name: dev-db
    restart: always
    env_file:
      - ../../.env
    ports:
      - "5432:5432"
    volumes:
      - postgres-dev-data:/var/lib/postgresql/data

volumes:
  postgres-dev-data:
    driver: local
