services:
  database:
    image: postgres:alpine
    container_name: test-db
    env_file:
      - "../../.env.test"
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    ports:
      - "5432:5432"
